### Reshaping and Resizing

In [2]:
import numpy as np

![](images/numpy-dimension-manipulation.png)

In [5]:
data = np.array([[1, 2], [3, 4]])
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [6]:
data.reshape(4)

array([1, 2, 3, 4])

In [13]:
np.array([1, 2, 3, 4]).reshape(2, 2)

array([[1, 2],
       [3, 4]])

***
The `np.ravel` (and its corresponding `ndarray` method) is a special case of reshape, which collapses all dimensions of an array and returns a flattened one-dimensional array with a length corresponding to the total number of elements in the original array. The `ndarray` method `flatten` performs the same function but returns a copy instead of a view.

In [7]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [8]:
data.flatten()

array([1, 2, 3, 4])

In [9]:
data.flatten().shape

(4,)

***
While `np.ravel` and `np.flatten` collapse the axes of an array into a one-dimensional array, it is also possible to introduce new axes into an array, either by using np.reshape or, when adding new empty axes, using indexing notation and the `np.newaxis` keyword at the place of a new axis. In the following example, the array data has one axis, so it should normally be indexed with a tuple with one element. However, if it is indexed with a tuple with more than one element, and if the extra indices in the tuple have the value `np.newaxis`, the corresponding new axes are added.

In [11]:
data = np.arange(0, 5)
column = data[:, np.newaxis]
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [12]:
row = data[np.newaxis, :]
row

array([[0, 1, 2, 3, 4]])

The `np.expand_dims` function can also be used to add new dimensions to an array, and in the preceding example, the expression 
* `data[:, np.newaxis]` is equivalent to `np.expand_dims(data, axis=1)`, and 
* `data[np.newaxis, :]` is equivalent to `np.expand_dims(data, axis=0)`. 
Here the axis argument specifies the location relative to the existing axes where the new axis is to be inserted.

***
NumPy provides the functions `np.vstack`, for vertical stacking of, for example, rows into a matrix, and `np.hstack` for horizontal stacking of, for example, columns into a matrix. The `np.concatenate` function provides similar functionality, but it takes a keyword argument axis that specifies the axis along which the arrays will be concatenated.

The shape of the arrays passed to `np.hstack`, `np.vstack`, and `np.concatenate` is important to achieve the desired type of array joining. For example, consider the following case: we have one-dimensional arrays of data and want to stack them vertically to obtain a matrix where the rows are made up of one-dimensional arrays. We can use `np.vstack` to achieve this.

In [13]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [14]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

***
If we instead want to stack the arrays horizontally to obtain a matrix where the arrays are the column vectors, we might first attempt something similar using `np.hstack`.

In [16]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [17]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

***
This stacks the arrays horizontally, but not in the way intended here. To make `np.hstack` treat the input arrays as columns and stack them accordingly, we need to make the input arrays two-dimensional arrays of `shape (1, 5)` rather than one-dimensional arrays of `shape (5,)`. As discussed earlier, we can insert a new axis by indexing with `np.newaxis`.

In [18]:
data = data[:, np.newaxis]
data

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [19]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

The number of elements in a NumPy array cannot be changed once the array has been created. For example, to insert, append, and remove elements from a NumPy array using the `np.append`, `np.insert`, and `np.delete` functions, a new array must be created and the data copied to it. It may sometimes be tempting to use these functions to grow or shrink the size of a NumPy array. But, due to the overhead of creating new arrays and copying the data, pre-allocating arrays with sizes is usually a good idea to pre-allocate them with sizes such that they do not need to be resized later.

***
### Vectorized Expressions

Many of these functions and operations act on arrays on an elementwise basis, and binary operations require all arrays in an expression to be of compatible size. The meaning of compatible size is normally that the variables in an expression represent either scalars or arrays of the same size and shape. More generally, a binary operation involving two arrays is well defined if the arrays can be broadcasted into the same shape and size.

### Broadcasting

<!-- ![](broadcasting.png) -->
<img src="images/broadcasting.png" width="600" height="600">

***
### Arithmetic Operations
The standard arithmetic operations with NumPy arrays perform elementwise operations. Consider, for example, the addition, subtraction, multiplication, and division of equal-sized arrays.

In [3]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
x + y

array([[ 6,  8],
       [10, 12]])

In [4]:

y - x

array([[4, 4],
       [4, 4]])

In [5]:
x * y

array([[ 5, 12],
       [21, 32]])

In [6]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [7]:
x * 2

array([[2, 4],
       [6, 8]])

In [8]:
2 ** x

array([[ 2,  4],
       [ 8, 16]])

In [9]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [10]:
(y / 2).dtype

dtype('float64')

#### If an arithmetic operation is performed on arrays with incompatible sizes or shapes, a `ValueError` exception is raised.

In [12]:
x =np.array([1,2,3,4]).reshape(2,2)
z = np.array([1,2,3,4])
x/z

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

array x has shape (2, 2) and the array z has shape (4,), which cannot be broadcasted into a form that is compatible with (2, 2). If, on the other hand, z has shape (2,), (2, 1), or (1, 2), then it can be broadcasted to the shape (2, 2) by effectively repeating the array z along the axis with length 1

In [47]:
z = np.array([[2, 4]])
z.shape

(1, 2)

In [48]:
z

array([[2, 4]])

In [49]:
x/z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [50]:
zz = np.concatenate([z, z], axis=0)
zz

array([[2, 4],
       [2, 4]])

In [51]:
zz2 = np.concatenate([z, z], axis=1)
zz2

array([[2, 4, 2, 4]])

In [52]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

***

In [58]:
x

array([[1, 2],
       [3, 4]])

In [59]:
z = np.array([[2], [4]])
z.shape

(2, 1)

In [60]:
z

array([[2],
       [4]])

In [61]:
x/z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [62]:
zz = np.concatenate([z, z], axis=1)
zz

array([[2, 2],
       [4, 4]])

In [63]:
x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

***
### Elementwise Functions
In addition to arithmetic expressions using operators, NumPy provides vectorized functions for elementwise evaluation of many elementary mathematical functions and operations. Table 2-7 gives a summary of elementary mathematical functions in NumPy.3 Each of these functions takes a single array (of arbitrary dimension) as input and returns a new array of the same shape, where for each element, the function has been applied to the corresponding element in the input array. The data type of the output array is not necessarily the same as that of the input array.

<img src="images/elementary-math-func.png" width="600" height="600">

the `np.sin` function (which takes only one argument) is used to compute the sine function for all values in the array.

In [64]:
x = np.linspace(-1, 1, 11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [65]:
y = np.sin(np.pi * x)
y

array([-1.22464680e-16, -5.87785252e-01, -9.51056516e-01, -9.51056516e-01,
       -5.87785252e-01,  0.00000000e+00,  5.87785252e-01,  9.51056516e-01,
        9.51056516e-01,  5.87785252e-01,  1.22464680e-16])

In [67]:
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [71]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [72]:
np.sin(x) ** 2 + np.cos(x) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<img src="images/elementary-math-func2.png" width="600" height="600">

#### Occasionally, it is necessary to define new functions that operate on NumPy arrays on an element-by-element basis. 
A good way to implement such functions is to express it in terms of existing NumPy operators and expressions. But when this is not possible, the `np.vectorize` function can be a convenient tool. This function takes a nonvectorized function and returns a vectorized function. For example, consider the following implementation of the Heaviside step function, which works for scalar input.

In [74]:
def heaviside(x):
    return 1 if x > 0 else 0
heaviside(-1)

0

In [75]:
heaviside(1.5)

1

#### However, unfortunately, this function does not work for NumPy array input.

In [80]:
x = np.linspace(-5,5,11)
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### Using `np.vectorize` the scalar Heaviside function can be converted into a vectorized function that works with NumPy arrays as input.

In [81]:
heaviside = np.vectorize(heaviside)
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

#### Although the function returned by `np.vectorize` works with arrays, it will be relatively slow since the original function must be called for each element in the array. There are much better ways to implement this function using arithmetic with Boolean-valued arrays

In [82]:
def heaviside(x):
    return 1.0 * (x > 0)

#### Nonetheless, np.vectorize can often be a quick and convenient way to vectorize a function written for scalar input.

***
### Aggregate Functions